import Head from "next/head";
import ImageUploading from "react-images-uploading";
import Toggle from "react-toggle";
import { useState } from "react";
import "react-toggle/style.css";

export default function Home() {
  const [images, setImages] = useState([]);
  const [numChoices, setNumChoices] = useState(null);
  const [areResultsShared, setAreResultsShared] = useState(false);
  const [isPollCreated, setIsPollCreated] = useState(false);
  const maxUpload = 12;

  const onChange = (imageList, addUpdateIndex) => {
    // data for submit
    console.log(imageList, addUpdateIndex);
    setImages(imageList);
    !numChoices && setNumChoices(imageList.length);
  };

  return (
    <div>
      <Head>
        <title>Image Poll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto max-w-lg px-4 flex flex-col items-center">
        <div className="text-2xl py-4">Image Poll</div>
        <div className="text-lg text-center">
          Image Poll enables you to ask your community to rank your photos. Use
          this to figure what is best for your dating profile, portfolio, etc.
        </div>
        <ImageUploading
          multiple
          value={images}
          onChange={onChange}
          maxNumber={maxUpload}
          dataURLKey="data_url"
        >
          {({
            imageList,
            onImageUpload,
            onImageUpdate,
            onImageRemove,
            isDragging,
            dragProps,
          }) => (
            <div className="py-4 text-center">
              <button
                className="px-16 py-4 border-solid border-2"
                onClick={onImageUpload}
                {...dragProps}
              >
                Upload photos
              </button>
              <div className="pt-4 grid gap-4 grid-cols-3">
                {imageList.map((image, index) => (
                  <div key={image["data_url"]} className="image-item">
                    <img src={image["data_url"]} alt="" width="100" />
                    <div className="image-item__btn-wrapper">
                      <button onClick={() => onImageUpdate(index)}>
                        Update
                      </button>
                      <button onClick={() => onImageRemove(index)}>
                        Remove
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </ImageUploading>
        {images.length > 1 && (
          <div className="text-center py-4">
            <div className="text-2xl py-4">Max Choices</div>
            <div className="flex justify-center">
              <button
                className="text-2xl px-4"
                disabled={numChoices < 3}
                onClick={() => setNumChoices(numChoices - 1)}
              >
                -
              </button>
              <div className="text-xl border-solid border-2 rounded-full px-4 py-2">
                {numChoices}
              </div>
              <button
                className="text-2xl px-4"
                disabled={numChoices > images.length - 1}
                onClick={() => setNumChoices(numChoices + 1)}
              >
                +
              </button>
            </div>
            <div className="flex justify-center py-4">
              <div className="px-2">Share results?</div>
              <label>
                <Toggle
                  defaultChecked={areResultsShared}
                  icons={false}
                  onChange={() => setAreResultsShared(!areResultsShared)}
                />
              </label>
            </div>
            {isPollCreated ? (
              <div className="flex flex-col text-center">
                <div className="text-lg pb-4">
                  Huzzah! Your poll has been created!
                </div>
                <div className="text-sm pb-4">
                  Send this link for voting
                  <div className="px-4 py-4 border-solid border-2 my-2 truncate max-w-xs">
                    https://www.imagepoll.com/vote
                  </div>
                </div>
                <div className="text-sm">
                  Use this link to see results
                  <div className="px-4 py-4 border-solid border-2 my-2 truncate max-w-xs">
                    https://www.imagepoll.com/resultshttps://www.imagepoll.com/resultshttps://www.imagepoll.com/results
                  </div>
                </div>
              </div>
            ) : (
              <button
                className="px-16 py-4 border-solid border-2"
                onClick={() => setIsPollCreated(true)}
              >
                Create Poll
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
